### ISSUE TITLE
differ dataset report different issue

### ISSUE THREAD

**Issue by ZQ8332** [CRazorback/AADG#3]
HI,

thank your excellent code. but i have some questions when i run it.

when i used python run.py --cfg experiments/optic_sinkhorn/diversity.yaml --output_dir output/
it raised 
    main()
  File "run.py", line 54, in main
    lanuch_mp_worker(search_worker, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search.py", line 33, in search_worker
    search_seg_dg_policy(gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg.py", line 330, in search_seg_dg_policy
    dis_criterion, model_optimizer, dis_optimizer, epoch, writer_dict, logger)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg.py", line 51, in pretrain
    dis_output = discriminator(feature.detach())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\WORKS\RLretinalseg\AADG-main\models\discriminator.py", line 53, in forward
    fe = self.dis(x)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

F:\WORKS\RLretinalseg\AADG-main>python run.py --cfg experiments/optic_sinkhorn/diversity.yaml --output_dir output/
[pyKeOps]: Warning, no cuda detected. Switching to cpu only.
Use GPU: 0 for training
=> creating model 'deeplabv3+' with 'mobilenet_v2
=> creating RNN controller
=> creating discriminator 'momentum_feature'
==> Loading train data from: ./dataset/Fundus/Domain1\train\ROIs/image/
==> Loading train data from: ./dataset/Fundus/Domain2\train\ROIs/image/
==> Loading train data from: ./dataset/Fundus/Domain3\train\ROIs/image/
-----Total number of images in train: 469
==> Loading test data from: ./dataset/Fundus/Domain4\test\ROIs/image/
-----Total number of images in test: 80
=> creating output\optic\diversity_2022-10-12-12-08
=> creating log\optic\deeplabv3+\diversity_2022-10-12-12-08_2022-10-12-12-08
[pyKeOps]: Warning, no cuda detected. Switching to cpu only.
[pyKeOps]: Warning, no cuda detected. Switching to cpu only.
[pyKeOps]: Warning, no cuda detected. Switching to cpu only.
[pyKeOps]: Warning, no cuda detected. Switching to cpu only.
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    main()
  File "run.py", line 54, in main
    lanuch_mp_worker(search_worker, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search.py", line 33, in search_worker
    search_seg_dg_policy(gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg.py", line 332, in search_seg_dg_policy
    dis_criterion, model_optimizer, dis_optimizer, epoch, writer_dict, logger)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg.py", line 51, in pretrain
    dis_output = discriminator(feature.detach())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\WORKS\RLretinalseg\AADG-main\models\discriminator.py", line 53, in forward
    fe = self.dis(x)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

when i used python run.py --cfg experiments/rvs_sinkhorn/diversity_ex.yaml --output_dir output/
it raised 
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    main()
  File "run.py", line 54, in main
    lanuch_mp_worker(search_worker, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\distributed.py", line 31, in lanuch_mp_worker
    main_worker(args.gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search.py", line 35, in search_worker
    search_seg2d_dg_policy(gpu, ngpus_per_node, config, args)
  File "F:\WORKS\RLretinalseg\AADG-main\search_dg_2d.py", line 288, in search_seg2d_dg_policy
    train_samplers, train_loader, test_loader = get_seg_dg_dataloader(config, args, batch_size, workers)
  File "F:\WORKS\RLretinalseg\AADG-main\data\dataloader.py", line 19, in get_seg_dg_dataloader
    testset = RetinalVesselSegmentation(dataroot, phase='test', splitid=cfg.DATASET.DG.TEST, transform=transform_test)
  File "F:\WORKS\RLretinalseg\AADG-main\data\vessel.py", line 67, in __init__
    self.image_list.append({'image': image_path, 'label': gtPath[idx], 'roi': roiPath[idx]})
IndexError: list index out of range

**Comment by H-CODE6** [comment]
Hello, I ran the new code, but TypeError still appears:__ init__ () Missing 1 required positional argument: 'classes' error. How do you solve this problem? We look forward to your reply.

**Comment by CRazorback** [comment]
Hi there, could you please re-pull the whole repo and run it again?

**Comment by H-CODE6** [comment]
Sorry, I found the problem. My Python version is 3.7, where<ENV>/lib/python 3.8/site packages/segmentation_ models_ There is no Flatten class in pytorch/base/modules. Could you please upload modules.py and let me replace it? Thank you.

**Comment by H-CODE6** [comment]
Thank you for your answer. I have solved all the problems and the code is ready to run. Thank you very much.
